import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FieldForm from "../components/Profile/FieldForm";

export default function Home() {
  let items = [];
  const setItems = es => {
      items = es;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FieldForm setGroups={setItems} groups={items} typesOfField={['string','int','array','Datetime']} dateFormats={['y/m/d','d/m/y']}/>
    </div>
  )
}
